#!/bin/sh
#
# Start aa-proxy-rs daemon
#
# For documentation and command line parameters go to:
# https://github.com/manio/aa-proxy-rs

DAEMON="aa-proxy-rs"
PIDFILE="/var/run/$DAEMON.pid"
AA_PROXY_RS_ARGS=""

RETVAL=0

case "$1" in
	start)
		printf "Starting $DAEMON: "
		i=0
		while [ ! -S /var/run/dbus/system_bus_socket ] && [ $i -lt 30 ]; do
			sleep 0.1
			i=$((i + 1))
		done
		start-stop-daemon -S -b -q -m -p "$PIDFILE" -x "/usr/bin/$DAEMON" -- $AA_PROXY_RS_ARGS
		RETVAL=$?
		[ $RETVAL = 0 ] && echo "OK" || echo "FAIL"
		;;
	stop)
		printf "Stopping $DAEMON: "
		start-stop-daemon -K -q -p "$PIDFILE"
		RETVAL=$?
		[ $RETVAL = 0 ] && echo "OK" || echo "FAIL"
		;;
	restart)
		$0 stop
		$0 start
		;;
	*)
		echo "Usage: $0 {start|stop}"
		;;
esac

exit $RETVAL
